name = "Spacey"
uuid = "6fa23216-6d9f-473e-ad34-00be7be2628b"
authors = ["Gus Hart <gus.hart@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MinkowskiReduction = "d617d09d-b3c0-43f1-8886-30d89b900f25"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "^1.2"
