name = "Spacey"
uuid = "6fa23216-6d9f-473e-ad34-00be7be2628b"
authors = ["Gus Hart <gus.hart@gmail.com>"]
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MinkowskiReduction = "d617d09d-b3c0-43f1-8886-30d89b900f25"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
MinkowskiReduction = "1.2"
julia = "1.2"
StatsBase = "0.33"